import './lib/setup';
import { ZClient } from './lib/structures/ZClient';
import { LogLevel } from '@sapphire/framework';
import { GatewayIntentBits, Partials } from 'discord.js';

const client = new ZClient({
	defaultPrefix: process.env.DEFAULT_PREFIX,
	regexPrefix: /^(hey +)?zeyr[,! ]/i,
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug
	},
	shards: 'auto',
	intents: [
		GatewayIntentBits.GuildMembers,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.MessageContent
	],
	partials: [Partials.Channel],
	loadMessageCommandListeners: true,
	subcommandsAdvanced: {
		nameCommandsAutogenerated: true
	}
});

const main = async () => {
	try {
		await client.init();
	} catch (error) {
		client.logger.fatal(error);
		client.destroy();
		process.exit(1);
	}
};

main();
