import './lib/setup';
import { ZClient } from './lib/structures/ZClient';
import { LogLevel } from '@sapphire/framework';
import {
	ActivityType,
	GatewayIntentBits,
	Options,
	Partials,
	PresenceUpdateStatus
} from 'discord.js';

const client = new ZClient({
	defaultPrefix: process.env.DEFAULT_PREFIX,
	regexPrefix: /^(hey +)?zeyr[\W ]/i,
	caseInsensitiveCommands: true,
	logger: {
		level: LogLevel.Debug
	},
	shards: 'auto',
	intents: [
		GatewayIntentBits.GuildMembers,
		GatewayIntentBits.GuildMessages,
		GatewayIntentBits.Guilds,
		GatewayIntentBits.MessageContent
	],
	partials: [Partials.Channel],
	makeCache: Options.cacheWithLimits(),
	presence: {
		activities: [
			{
				name: 'with tags',
				type: ActivityType.Playing
			}
		],
		status: PresenceUpdateStatus.Online
	},
	allowedMentions: {
		parse: []
	},
	loadMessageCommandListeners: true,
	subcommandsAdvanced: {
		nameCommandsAutogenerated: true
	},
	api: {
		prefix: 'v0',
		origin: '*',
		listenOptions: {
			port: 3000
		}
	}
});

const main = async () => {
	try {
		await client.init();
	} catch (error) {
		client.logger.fatal(error);
		client.destroy();
		process.exit(1);
	}
};

main();
